application: particle-979
version: 1
runtime: go
api_version: go1

handlers:
- url: /test
  static_dir: test
- url: /particle
  static_dir: particle
- url: /common
  static_dir: common
- url: /stock
  static_dir: stock
- url: /card
  static_dir: card
- url: /.*
  script: _go_app
