application: particle-979
version: 1
runtime: go
api_version: go1

handlers:
- url: /particle
  static_dir: particle
- url: /common
  static_dir: common
- url: /stock
  static_dir: stock
- url: /cocoon
  static_dir: cocoon
- url: /.*
  script: _go_app
