application: particle-979
version: 1
runtime: go
api_version: go1
default_expiration: "7d"
handlers:
- url: /duelsys
  static_dir: duelsys
- url: /collectmmo
  static_dir: collectmmo
- url: /tableGameCreator
  static_dir: tableGameCreator
- url: /manager
  static_dir: manager
- url: /test
  static_dir: test
- url: /particle
  static_dir: particle
- url: /common
  static_dir: common
- url: /stock
  static_dir: stock
- url: /card_new
  static_dir: card_new
- url: /card
  static_dir: card
- url: /deckWiki
  static_dir: deckWiki
- url: /.*
  script: _go_app

inbound_services:
- channel_presence