runtime: go
api_version: go1
threadsafe: true
handlers:
- url: /works
  static_dir: www/works
- url: /sgs_online
  static_dir: www/sgs_online
- url: /contestsys
  static_dir: www/contestsys
- url: /collectmmo
  static_dir: www/collectmmo
- url: /tableGameCreator
  static_dir: www/tableGameCreator
- url: /manager
  static_dir: www/manager
- url: /test
  static_dir: www/test
- url: /particle
  static_dir: www/particle
- url: /common
  static_dir: www/common
- url: /stock
  static_dir: www/stock
- url: /card_new
  static_dir: www/card_new
- url: /card
  static_dir: www/card
- url: /deckWiki
  static_dir: www/deckWiki
- url: /xiaogenban
  static_dir: www/xiaogenban
- url: /.*
  script: _go_app
  secure: always
